name: simpler
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.0
  - torchvision=0.16.0
  - torchaudio=2.1.0
  - tensorflow-gpu=2.15.0
  - numpy=1.24.4
  - tensorflow-datasets=4.8.2
  - tensorflow-hub=0.16.0
  - tensorflow-probability
  - ipython=8.22.2
  - mediapy=1.2.0
  - gsutil
  - pip:
    - typing-extensions==4.8.0
    - tf_agents==0.18.0
    - dm-reverb[tensorflow]==0.14.0
    - matplotlib
    - dlimp @ git+https://github.com/kvablack/dlimp@d08da3852c149548aaa8551186d619d87375df08
    - plotly
    - distrax==0.1.5
    - flax==0.8.1
    - ml_collections
    - wandb
    - einops
    - transformers
    - scipy==1.12.0
    - coacd





